apiVersion: v1
kind: Service
metadata:
  name: obs-frontend-rails
  labels:
    app: obs-frontend-rails
spec:
  ports:
    - port: 7443
      targetPort: 443
  selector:
    app: obs-frontend-rails
  type: NodePort
