apiVersion: v1
kind: Pod
metadata:
  name: test-leap-pod
spec:
  containers:
  - name: test-leap-cont
    image: registry.opensuse.org/opensuse/leap:15
    tty: true
    securityContext:
      privileged: true
