---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-service
  labels:
    app: obs-service
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: obs-service
  template:
    metadata:
      labels:
        app: obs-service
    spec:
      containers:
      - name: obs-service
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-service:0.0.1
