apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-worker-deployment
  labels:
    app: obs-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: obs-worker
  template:
    metadata:
      labels:
        app: obs-worker
    spec:
      containers:
      - name: obs-worker
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-worker:0.0.1
        ports:
        - containerPort: 8888
        command: ["/usr/lib/obs/server/containerworker"]
