apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: obs-frontend-rails
  labels:
    app: obs-frontend-rails
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: obs-frontend-rails
    spec:
      containers:
        - image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-frontend-rails:0.0.1
          name: obs-frontend-rails
          #env:
          #- name: MYSQL_ROOT_PASSWORD
          #  value: opensuse
          ports:
          - containerPort: 443
            name: https
          stdin: true
          tty: true
