---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: obs-memcached
  labels:
    app: obs-memcached
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: obs-memcached
    spec:
      containers:
        - image: kube-registry.kube-system.svc.cluster.local:5000/obs-memcached:latest
          name: obs-memcached
          ports:
          - containerPort: 11211
            name: memcached
