---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-repserver
  labels:
    app: obs-repserver
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: obs-repserver
  template:
    metadata:
      labels:
        app: obs-repserver
    spec:
      volumes:
      - name: obs-repserver
        emptyDir: {}
      containers:
      - name: obs-signer
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-signer:0.0.1
        volumeMounts:
        - name: obs-repserver
          mountPath: /srv/obs
      - name: obs-repserver
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-repserver:0.0.1
        ports:
        - containerPort: 5352
        volumeMounts:
        - name: obs-repserver
          mountPath: /srv/obs
      - name: obs-dispatch
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-dispatch:0.0.1
        volumeMounts:
        - name: obs-repserver
          mountPath: /srv/obs
      - name: obs-scheduler
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-scheduler:0.0.1
        env:
          - name: OBS_SCHEDULER_ARCH
            value: x86_64
        volumeMounts:
        - name: obs-repserver
          mountPath: /srv/obs
      - name: obs-warden
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-warden:0.0.1
        volumeMounts:
        - name: obs-repserver
          mountPath: /srv/obs
      - name: obs-publish
        image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-publish:0.0.1
        volumeMounts:
        - name: obs-repserver
          mountPath: /srv/obs
