---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: obs-memcached
  labels:
    app: obs-memcached
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: obs-memcached
    spec:
      containers:
        - image: registry.opensuse.org/home/m0ses/obs/server/containers/containers/obs-memcached:0.0.1
          name: obs-memcached
          ports:
          - containerPort: 11211
            name: memcached
